# Generated by Django 4.0.6 on 2022-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('Python', 'Python'), ('Java', 'Java')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
