# Generated by Django 4.0.6 on 2022-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('question', models.TextField(verbose_name='問題文')),
                ('select1', models.CharField(max_length=200, verbose_name='選択１')),
                ('select2', models.CharField(max_length=200, verbose_name='選択2')),
                ('select3', models.CharField(max_length=200, verbose_name='選択3')),
                ('select4', models.CharField(max_length=200, verbose_name='選択4')),
                ('select5', models.CharField(max_length=200, verbose_name='選択5')),
                ('answer', models.CharField(max_length=200, verbose_name='答え')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('question', models.TextField(verbose_name='問題文')),
                ('code', models.TextField(verbose_name='プログラム')),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C')], max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
