# Generated by Django 4.0.6 on 2022-11-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_knowledgepost_questionpost_alter_program_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
        migrations.RemoveField(
            model_name='program',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.TextField(default=2, verbose_name='プログラム'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='content',
            field=models.TextField(verbose_name='問題文'),
        ),
    ]
