# Generated by Django 4.0.6 on 2022-12-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_java_program_python_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Knowledge',
            new_name='Q_knowledge',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
