# Generated by Django 4.0.6 on 2022-12-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_rename_knowledge_q_knowledge_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C_Program',
            new_name='Python2_Program',
        ),
    ]
