# Generated by Django 4.0.6 on 2022-12-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_rename_python_program_c_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Python2_Program',
            new_name='Python_Program',
        ),
    ]
